pipeline {
  environment {
    dockerimagename = "app"
    dockerImage = ""
  }
  agent any
  stages {
    stage('Checkout Source') {
      steps {
        git branch: 'main', url: 'https://github.com/alexanderm33/app.git'
      }
    }
    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build dockerimagename
        }
      }
    }
    stage('Pushing Image') {
      environment {
               registryCredential = var.yc_token
           }
      steps{
        script {
          docker.withRegistry( 'cr.yandex/crp1538ujt8n2dce092s/', registryCredential ) {
            dockerImage.push("latest")
          }
        }
      }
    }
  }
}